version: '3.8'

services:
  aorist-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aorist-backend
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - aorist-mongo
      - aorist-redis
    restart: always

  aorist-mongo:
    image: mongo:6.0
    container_name: aorist-mongo
    environment:
      MONGO_INITDB_DATABASE: AoristHomes
    volumes:
      - mongo-data:/data/db
    restart: always

  aorist-redis:
    image: redis:7-alpine
    container_name: aorist-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  mongo-data:
  redis-data: