spring:
  config:
    import: "optional:classpath:keys.properties"
  data:
    mongodb:
      uri: mongodb://aorist-mongo:27017/AoristHomes
  secret.key: ${secret.key:${JWT_SECRET:dummySecret}}
  consumer.key: ${consumer.key:${CONSUMER.KEY:dummyConsumerKey}}
  consumer.secret: ${consumer.secret:${CONSUMER.SECRET:dummyConsumerSecret}}
  auth.url: ${authUrl:${AUTH.URL:https://pay.pesapal.com/v3/api/Auth/RequestToken}}
  payment.url: ${paymentUrl:${PAYMENT.URL:https://pay.pesapal.com/v3/api/Transactions/SubmitOrderRequest}}
  callback.url: ${callback.url:${CALLBACK.URL:https://your-default-callback}}
  notification.id: ${notification.id:${NOTIFICATION.ID:defaultNotificationId}}

  status.url: ${Status_url:${STATUS.URL:https://pay.pesapal.com/v3/api/Transactions/GetTransactionStatus}}

