spring:
  config:
    import: "optional:classpath:keys.properties"
  data:
    mongodb:
      uri: mongodb://aorist-mongo:27017/AoristHomes
  secret-key: ${secret_key:${JWT_SECRET:dummySecret}}
  consumer-key: ${consumer_key:${CONSUMER_KEY:dummyConsumerKey}}
  consumer-secret: ${consumer_secret:${CONSUMER_SECRET:dummyConsumerSecret}}
  auth-url: ${authUrl:${AUTH_URL:https://pay.pesapal.com/v3/api/Auth/RequestToken}}
  payment-url: ${paymentUrl:${PAYMENT_URL:https://pay.pesapal.com/v3/api/Transactions/SubmitOrderRequest}}
  callback-url: ${callback_url:${CALLBACK_URL:https://your-default-callback}}
  notification-id: ${notification_id:${NOTIFICATION_ID:defaultNotificationId}}

  status-url: ${Status_url:${STATUS_URL:https://pay.pesapal.com/v3/api/Transactions/GetTransactionStatus}}

