spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/AoristHomes
    redis:
      host: localhost
      port: 6379
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    AoristHomes: DEBUG
    org.springframework.security: DEBUG